version: "3.8"

services:
  ####################################
  # Atomic Microservice: account-service
  ####################################
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "30009:8080"
  ####################################
  # Atomic Microservice: frontend
  ####################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "30000:3000"